### ISSUE TITLE
hhelp

### ISSUE THREAD

**Issue by yekayee** [IRIS-Team/TwitterCheckr#2]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from util.api.core import banner, menu
  File "C:\laragon\www\Twitter\TwitterCheckr\util\api\__init__.py", line 1, in <module>
    from util.api.core import *
  File "C:\laragon\www\Twitter\TwitterCheckr\util\api\core.py", line 9, in <module>
    from util.scraper.core import *
  File "C:\laragon\www\Twitter\TwitterCheckr\util\scraper\__init__.py", line 1, in <module>
    from util.scraper.core import *
  File "C:\laragon\www\Twitter\TwitterCheckr\util\scraper\core.py", line 2, in <module>
    from util.duckduckgo import *
  File "C:\laragon\www\Twitter\TwitterCheckr\util\duckduckgo\__init__.py", line 1, in <module>
    from util.duckduckgo.core import *
  File "C:\laragon\www\Twitter\TwitterCheckr\util\duckduckgo\core.py", line 4, in <module>
    class DuckDuckGo:
  File "C:\laragon\www\Twitter\TwitterCheckr\util\duckduckgo\core.py", line 6, in DuckDuckGo
    def search(search_query: str) -> list[tuple[str, str]]:
TypeError: 'type' object is not subscriptable

**Comment by sequel1337** [comment]
are ya using python 3.9 ?!

**Comment by rpie** [comment]
This program uses Python 3.9 functions that aren't in any other version so switch to 3.9 and it should fix the issue :)

_HellSec_
